### PR TITLE
Adds option to use preemtible instances

### PR DESCRIPTION
**Pull request by halfdanrump**
See #55

This PR is a very simple fix. There's no handling of the event that an instance is pre-empted. So using this option is of course on the user's own risk. But I think it's OK, since people who know about preemptible VMs also knows the risks.

### CODE REVIEW

**Comment by halfdanrump** [comment]
Ugh sorry, seems like  I forked from the wrong repo....

**Comment by ckemere** [comment]
Yep - dask/dask-kubernetes is the master

**Comment by halfdanrump** [comment]
@ckemere Yep, but my search engine brought me here for some reason, and I didn't look too closely before forking 😆 

By the way, some of the commits you did sound pretty important (jupyter notebook HTTPS and security fixes). Any plans of merging into dask/dask-kubernetes?

**Comment by ckemere** [comment]
The patch I made doesn't actually make things that much more secure, as you have to click past an unsigned certificate. So probably not great for production. The jupyter-stacks (which is where I got it from) have a more complex setup with various command line options to enable different features. I'll post an issue and see if the dask folks want to enable it.

**Comment by halfdanrump** [comment]
Yeah, that'd be great :). I just assumed that everything was working securely out of the box, but now I'm not sure if I can use this tool to handle sensitive data.

**Pull request closed without merging**
